export default users =[
    {
        id:1,
        email:'user1@gmail.com',
        username:'user1',
        password:'password',
        userToken:'token123'
    },
    {
        id:2,
        email:'user2@gmail.com',
        username:'user2',
        password:'password',
        userToken:'token12345'
    },
    {
        id:3,
        email:'testuser@gmail.com',
        username:'testuser',
        password:'password',
        userToken:'testtoken'
    },
]